apiVersion: v1
kind: Pod
metadata:
  name: my-result-app-pod
  labels:
    author: ravi
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result